apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-7qxo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-7qxo
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-7qxo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-7qxo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-7qxo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-qhvr-tenant/nodejs-users/simple-nodejs-app-7qxo@sha256:e3486facfd10dd0f82f0209b31630c355208b0dd821608f0d389f57287f45209
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
